
import java.util.logging.Level;
import java.util.logging.Logger;
import helper.Exercise;
import java.io.BufferedReader;
import java.io.FileReader;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Vector;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cjwn
 */
public class WorkoutLibraryUI extends javax.swing.JFrame {

    private static final String workoutDataFilePath = "workouts.csv";
    private HashMap<String, Exercise> exerciseMap  = new HashMap<String, Exercise>();
    private String[] categoryStrings = {"Strength", "Cardio"};
    private String[] exerciseNames;
    private Vector<String> strengthExercises = new Vector<String>();
    private Vector<String> cardioExercises = new Vector<String>();
    /**
     * Creates new form WorkoutLibraryUI
     */
    public WorkoutLibraryUI() throws Exception {
        initComponents();
        setLocationRelativeTo(null);    //puts the window in the center of the screen
        setVisible(true);               // show the window
        loadExerciseMap();              // load the exercises in the the map
        loadInitialListData();
        
    }
    
    /**
     * Takes the exercises from the map and loads them into respective vectors
     */
    public void loadInitialListData() {
        // initialize an array to store the names of the exercises
        exerciseNames = new String[exerciseMap.size()];
        
        // iterate through the keys of the exerciseMap and add to either 
        // the strength or cardio categories
        int i = 0;
        int numOfStrengthExercises = 0;
        int numOfCardioExercises = 0;
        
        for (String key : exerciseMap.keySet()) {
            exerciseNames[i] = key;
           /* 
            if (exerciseMap.get(key).getCategory().toString() == categoryStrings[0]) {
                numOfStrengthExercises++;
                //strengthExercises.add(key);
                //System.out.println("Strength Exercise Added");
            } else {
                numOfCardioExercises++;
                //cardioExercises.add(key);
                //System.out.println("Cardio Exercise Added");
            }
            */
            i++;
        }
        
        exerciseList.setListData(strengthExercises);
    }
    
    /**
     * 
     * Loads the list of exercises from the csv file into the exercise map
     * @throws Exception 
     */
    public void loadExerciseMap() throws Exception {
        BufferedReader csvFile = new BufferedReader(new FileReader(workoutDataFilePath));
        
        String dataRow = csvFile.readLine();
        
        while (dataRow != null) {
            String[] dataArray = dataRow.split(",");
            String cat = dataArray[0];
            String subCat = dataArray[1];
            String name = dataArray[2];
            String desc = "";
            
            for (int i = 3; i < dataArray.length; i++) {
                desc += "," + dataArray[i];
            }
            desc = desc.substring(2, desc.length()-1);
            
            Exercise ex = new Exercise(name, cat, subCat, desc);
            exerciseMap.put(name, ex);
            if (cat.equals("Strength")) {
                strengthExercises.add(name);
                //System.out.println("Added strength exercise: " + name);
            } else {
                cardioExercises.add(name);
                //System.out.println("Added cardio exercise: " + name);
            }
            
            dataRow = csvFile.readLine();
        }
        csvFile.close();
    }
    
    /**
     * 
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        exerciseList = new javax.swing.JList<>();
        backButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        strengthRadioButton = new javax.swing.JRadioButton();
        cardioRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(490, 450));
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Workout Library");
        titleLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        exerciseList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pushups", "Squats", "Shoulder Press", "Plank" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        exerciseList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        exerciseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exerciseListMouseClicked(evt);
            }
        });
        exerciseList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                exerciseListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(exerciseList);

        backButton.setText("<< Go Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        descriptionTextArea.setEditable(false);
        descriptionTextArea.setColumns(20);
        descriptionTextArea.setLineWrap(true);
        descriptionTextArea.setRows(5);
        descriptionTextArea.setText("Click on an exercise to learn more about it!");
        descriptionTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(descriptionTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
        );

        jLabel1.setText("Pick a category:");

        strengthRadioButton.setText("Strength");
        strengthRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strengthRadioButtonActionPerformed(evt);
            }
        });

        cardioRadioButton.setText("Cardio");
        cardioRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardioRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(strengthRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(cardioRadioButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(strengthRadioButton)
                    .addComponent(cardioRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(backButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new HomeScreenUI();
    }//GEN-LAST:event_backButtonActionPerformed

    private void exerciseListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_exerciseListValueChanged
        // TODO add your handling code here:
        //Exercise ex = exerciseMap.get(exerciseList.getSelectedValue());
        //descriptionTextArea.setText(ex.getDescription());
    }//GEN-LAST:event_exerciseListValueChanged

    private void exerciseListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exerciseListMouseClicked
        // TODO add your handling code here:
        Exercise ex = exerciseMap.get(exerciseList.getSelectedValue());
        descriptionTextArea.setText(ex.getDescription());
    }//GEN-LAST:event_exerciseListMouseClicked

    private void strengthRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strengthRadioButtonActionPerformed
        // TODO add your handling code here:
        exerciseList.setListData(strengthExercises);
        exerciseList.updateUI();
    }//GEN-LAST:event_strengthRadioButtonActionPerformed

    private void cardioRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardioRadioButtonActionPerformed
        // TODO add your handling code here:
        exerciseList.setListData(cardioExercises);
        exerciseList.updateUI();
    }//GEN-LAST:event_cardioRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkoutLibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkoutLibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkoutLibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkoutLibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new WorkoutLibraryUI().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(WorkoutLibraryUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JRadioButton cardioRadioButton;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JList<String> exerciseList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton strengthRadioButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
